name: Sync branch

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    name: Update v1 branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Only run on original repository
    if: ${{ github.repository_id == 635386785 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          ref: main
      - uses: connor-baer/action-sync-branch@066ffc273774493f6327c8f373ef14228961af9c # v2.0.1
        with:
          branch: v1
          token: ${{ secrets.GITHUB_TOKEN }}
          # Force push is enabled since v1 is supposed to be an exact copy of main until breaking changes are made
          force: true
