name: Sync branch

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    name: Update v1 branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Only run on original repository
    if: ${{ github.repository_id == 635386785 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: main
      - uses: connor-baer/action-sync-branch@4f44fe844a1a3f53676699cfe74453820a38ca65 # v2.0.2
        with:
          branch: v1
          token: ${{ secrets.GITHUB_TOKEN }}
          # Force push is enabled since v1 is supposed to be an exact copy of main until breaking changes are made
          force: true
